// src/redux/actions/actionTypes.js

// Cinema Action Types
export const FETCH_CINEMAS_REQUEST = 'FETCH_CINEMAS_REQUEST';
export const FETCH_CINEMAS_SUCCESS = 'FETCH_CINEMAS_SUCCESS';
export const FETCH_CINEMAS_FAILURE = 'FETCH_CINEMAS_FAILURE';

// Movie Action Types
export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

// Upcoming Movie Action Types
export const FETCH_UPCOMING_MOVIES_REQUEST = 'FETCH_UPCOMING_MOVIES_REQUEST';
export const FETCH_UPCOMING_MOVIES_SUCCESS = 'FETCH_UPCOMING_MOVIES_SUCCESS';
export const FETCH_UPCOMING_MOVIES_FAILURE = 'FETCH_UPCOMING_MOVIES_FAILURE';
